#164797148 Create User Profile feature
andela/zinnia-ah-backend pull request #33
Opened 2019-04-06 20:15 UTC by eben-k

#### What does this PR do?
Has user profile update and viewing feature created

#### Description of Task to be completed?
* Write unit tests
*  Create update user profile endpoint
* Create get user profile endpoint

#### How should this be manually tested?
* Clone the repo,
* Run npm install toInstall all dependencies,
* Create .env file using the .env.example as a guide and enter you environment variables
* Run npm test
* Run npm run start:dev,
* On Postman, PUT json/application required inputs to localhost:3000/api/v1/user/:userId
* On Postman, GET json/application  to localhost:3000/api/v1/user/:username

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?(if applicable)
#164797148

#### Screenshots
![image](https://user-images.githubusercontent.com/38259391/55674763-ec181380-58b0-11e9-9f9e-02cc069cdb1a.png)
![image](https://user-images.githubusercontent.com/38259391/55674773-110c8680-58b1-11e9-9b9b-113c4690e435.png)

2019-04-06 20:54 UTC, musonant commented
Do you have ESLint and Prettier extensions installed on your text editor? It would help prevent a lot of the issues pointed out by Hound.

2019-04-08 11:40 UTC, Japhethca commented on src/db/models/User.js
>    });
lets remove this comment.

2019-04-08 11:41 UTC, Japhethca commented on src/db/models/User.js
> +  // associations can be defined here
let's remove this comment.

2019-04-08 11:44 UTC, Japhethca commented on src/tests/db/controller/user.test.js
> +      // .set('Authorization', firstUserToken);
let's remove this comment.

2019-04-08 11:44 UTC, Japhethca commented on src/tests/db/controller/user.test.js
> +    // .set('Authorization', firstUserToken);
same as above

2019-04-08 13:56 UTC, eben-k commented on src/db/models/User.js
> +  // associations can be defined here
Okay.  Done

2019-04-09 08:56 UTC, Japhethca commented on src/routes/index.js
> +// const { verifyToken, getUserId } = Jwt;
Let's remove this comment here.

2019-04-09 11:35 UTC, eben-k commented on src/routes/index.js
> +// const { verifyToken, getUserId } = Jwt;
It has been removed

2019-04-09 11:39 UTC, eben-k commented on src/routes/index.js
> +// const { verifyToken, getUserId } = Jwt;
Done!

2019-04-15 09:11 UTC, Japhethca commented on src/routes/controllers/users.controller.js
> +  const { url } = req;
we can destructure our variables in one line. 
```javascript 
const {url, user} = req;
```

2019-04-15 09:14 UTC, Japhethca commented on src/routes/controllers/users.controller.js
> +    if (url.includes('profiles')) {
We can create a new route/endpoint for this.

2019-04-15 09:39 UTC, Japhethca commented on src/routes/utils/helpers.js
> +import jwt from 'jsonwebtoken';
we can delete this file

2019-04-15 09:41 UTC, Japhethca requested changes
just few changes to make.

2019-04-16 09:05 UTC, Japhethca approved these changes

2019-04-16 09:07 UTC, merged